config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :teams
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :team
    belongs_to :user

    accepts_nested_attributes_for :team
    include PublicActivity::Model
	tracked owner: Proc.new { |controller, model| controller.current_user }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("created_at DESC")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
    @teams = Team.where('id = ?', current_user.team_id)
  end

  # GET /projects/1/edit
  def edit
    @teams = current_user.teams
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :team_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

	<% if !current_user.team_id.blank? %>
   <div class="field">
   	<div class="control">
   		<%= f.input :name, input_html: { class: "input" }, wrapper: false, label_html: { class: "label"} %>
   	</div>
   </div>
   <div class="field">
   	<div class="control">
   		<%= f.input :description, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label"} %>
   	</div>
   </div>

   <div class="field">
   	<div class="control">
   		<label class="label">Team</label>
   		<div class="control has-icons-left">
   			<span class="select">
   				<%= f.input_field :team_id, collection: @teams, prompt: "Select team" %>
   			</span>
   			<span class="icon is-small is-left">
   				<i class="fa fa-users"></i>
   			</span>
   		</div>
   	</div>
   </div>

   <div class="field">
   	<div class="control">
   		<%= f.button :submit, class: "button is-link" %>
   	</div>
   </div>
	<% else %>
	
		<article class="message is-warning">
			<div class="message-body">
				<strong>It looks as though you are not part of a team yet!</strong>
				<p>You can create a team or get invited by another user to join.</p>
				<br />
				<%= link_to 'Create a team', new_team_path, class:'button' %>
			</div>
		</article>

	<% end %>

<% end %>

app/views/projects/edit.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-2">Editing Project</h1>
		<%= render 'form', project: @project %>
	</div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-2">New Project</h1>
	
		<%= render 'form', project: @project %>
	<br />
	<%= link_to 'Back', projects_path, class:'button' %>
	</div>
</div>

app/views/projects/show.html.erb
<section class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-9">
				<h1 class="title is-2"><%= @project.name %></h1>
				<h2 class="subtitle is-5 has-text-weight-light"><span class="icon is-small has-text-weight-lighter"><i class="fa fa-users"></i>&nbsp; &nbsp;</span> <%= link_to @project.team.name, team_path(@project.team) %></h2>
				<div class="level">
					<div class="level-left">
						<p>Created on
							<%= verbose_date(@project.created_at) %> by <%= @project.user.name %> / Modified
							<%= time_ago_in_words(@project.updated_at) %></p>
					</div>
					<div class="level-right">
						<div class="buttons">
							<%= link_to 'Edit Project', edit_project_path(@project), class:'button' %>
							<%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure'}, class:'button is-danger is-outlined' %> 
						</div>
					</div>
				</div>
				<hr />
				<div class="content">
					<%= @project.description.html_safe %>
				</div>
			</div>
		</div>
	</div>
</section>